"""add institution catalog and venue link

Revision ID: 258fc3dd0647
Revises: 9dcbd31f1793
Create Date: 2026-07-10 19:25:05.271816

"""
from alembic import op
import sqlalchemy as sa


revision = '258fc3dd0647'
down_revision = '9dcbd31f1793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.Enum('school', 'college', 'university', 'museum', 'library', 'other', name='institution_type'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_institution_source_extid')
    )
    op.create_index(op.f('ix_institutions_city'), 'institutions', ['city'], unique=False)
    op.create_index(op.f('ix_institutions_latitude'), 'institutions', ['latitude'], unique=False)
    op.create_index(op.f('ix_institutions_longitude'), 'institutions', ['longitude'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_region'), 'institutions', ['region'], unique=False)
    op.add_column('venues', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_venues_institution_id'), 'venues', ['institution_id'], unique=False)
    op.create_foreign_key(
        'fk_venues_institution_id', 'venues', 'institutions',
        ['institution_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('fk_venues_institution_id', 'venues', type_='foreignkey')
    op.drop_index(op.f('ix_venues_institution_id'), table_name='venues')
    op.drop_column('venues', 'institution_id')
    op.drop_index(op.f('ix_institutions_region'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_longitude'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_latitude'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_city'), table_name='institutions')
    op.drop_table('institutions')
    sa.Enum(name='institution_type').drop(op.get_bind(), checkfirst=True)
